name: Github Actions Linter
on:
  pull_request: 
    branches: [develop, staging, master]
    types: [opened, synchronize]
  push:
    branches: [develop, staging, master]

jobs:
  main:
    name: Test DAG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build . -t tester:latest
      - name: Run Docker 
        run: docker run -e TESTS_FOLDER=tests -e DAG_FOLDER=dags -v /home/runner/work/github-data-flow-example/github-data-flow-example:/airflow tester:latest


